kind: ReplicaSet
apiVersion: apps/v1
metadata: 
  name: myapp2-rs 

spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: myapp2      
  template: 
    metadata:  #Dictionary /Map
      name: my-app2
      labels: # Dic
        app: myapp2
    spec:
      containers:  #List 
        - name: myapp2-container 
          image: tomcat:latest
          ports: 
            - containerPort: 8080
       