apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: my-nginx-app
  labels: 
    app: my-nginx-app
    tier: nginx
spec: 
  replicas: 3 
  selector: 
    matchLabels:  
        app: my-nginx-app
  template: 
    metadata: 
      labels: 
        app: my-nginx-app
        tier: nginx
    spec: 
      containers: 
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80
