apiVersion: v1
kind: Service 
metadata: 
  name: nginx-nodeport-service 
  labels: 
    app: my-nginx-app
    tier: nginx
spec: 
  type: NodePort
  selector: 
    app: my-nginx-app
      
  ports: 
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32142